# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ac64dafc492110732a33298e925e9973962ab07cb7e6be1f29ab4a0f5f65e4acfc243f19288220f60a2e8d8903f10c65fca52c316e89e4d543c52e4749df7d

test:
  secret_key_base: 3807889cb9a2f0d01c166a9f8952e8636ccba3566d10e0a3409f9752a10e26dc90e0c5265d03d2550625b29e5f719fdde189ec0e2411f9b276e9fc37550162e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
